name: Rails Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: shelf
          POSTGRES_PASSWORD: shelf
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Install dependencies
      run: -
        bundle install
        yarn install --check-files
    - name: Setup database
      env:
        DATABASE_URL: 'postgres://shelf:@localhost/shelf'
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rails db:setup
    - name: Run tests
      run: bundle exec rails test
